
import java.awt.Dimension;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henyr
 */
public class awal extends javax.swing.JFrame {

    /**
     * Creates new form awal
     */
    public awal() {
        initComponents();
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_login = new javax.swing.JButton();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        kepanjangan = new javax.swing.JLabel();
        bt_daftar = new javax.swing.JButton();
        try {
            bg_halawal =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "awal_bg_halawal");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 390));
        getContentPane().setLayout(null);

        bt_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        bt_login.setText("LOGIN");
        bt_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login);
        bt_login.setBounds(470, 270, 120, 50);

        judul1.setFont(new java.awt.Font("STHupo", 1, 36)); // NOI18N
        judul1.setForeground(new java.awt.Color(212, 212, 212));
        judul1.setText("TAQUMON APPLICATION");
        getContentPane().add(judul1);
        judul1.setBounds(130, 50, 440, 50);

        judul2.setFont(new java.awt.Font("STHupo", 1, 36)); // NOI18N
        judul2.setForeground(new java.awt.Color(204, 102, 0));
        judul2.setText("TAQUMON APPLICATION");
        getContentPane().add(judul2);
        judul2.setBounds(130, 50, 426, 40);

        kepanjangan.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        kepanjangan.setForeground(new java.awt.Color(255, 153, 0));
        kepanjangan.setText("\"Tahfidzul Qur’an Monitoring Aplication\"");
        getContentPane().add(kepanjangan);
        kepanjangan.setBounds(170, 100, 350, 40);

        bt_daftar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        bt_daftar.setText("DAFTAR");
        bt_daftar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_daftar);
        bt_daftar.setBounds(50, 270, 110, 50);
        getContentPane().add(bg_halawal);
        bg_halawal.setBounds(0, 0, 640, 360);

        setSize(new java.awt.Dimension(658, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_daftarActionPerformed
        new daftar ().setVisible (true);
         this.setVisible(false);
    }//GEN-LAST:event_bt_daftarActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        new PilihanLogin ().setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new awal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_halawal;
    private javax.swing.JButton bt_daftar;
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel kepanjangan;
    // End of variables declaration//GEN-END:variables
}
