/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author amirul
 */
public class cek_hafalan_terakhir_1 extends javax.swing.JFrame {

    /**
     * Creates new form tambahkan_hafalan
     */
    public cek_hafalan_terakhir_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void GetData() {
        try {
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql = stm.executeQuery("select * from cari");

        } catch (Exception e) {
        }
    }
    String[] data;
    String nime = "";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        text_nim = new javax.swing.JTextField();
        text_ayat = new javax.swing.JTextField();
        text_hari_tanggal = new javax.swing.JTextField();
        Jlabel_nim = new javax.swing.JLabel();
        Jlabel_tanggal = new javax.swing.JLabel();
        Jlabel_juz = new javax.swing.JLabel();
        Jlabel_surah = new javax.swing.JLabel();
        surah = new javax.swing.JComboBox<>();
        hapus = new javax.swing.JButton();
        Jlabel_ayat = new javax.swing.JLabel();
        text_juz = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        bg_cek_hafalan_terakhir_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        getContentPane().add(text_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 200, 40));
        getContentPane().add(text_ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 100, 30));

        text_hari_tanggal.setForeground(new java.awt.Color(153, 153, 153));
        text_hari_tanggal.setText("dd/mm/yy");
        getContentPane().add(text_hari_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 30));

        Jlabel_nim.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        Jlabel_nim.setText("NIM Mahasantri");
        getContentPane().add(Jlabel_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 50));

        Jlabel_tanggal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_tanggal.setText("Tanggal");
        getContentPane().add(Jlabel_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        Jlabel_juz.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_juz.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_juz.setText("Juz");
        getContentPane().add(Jlabel_juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));

        Jlabel_surah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_surah.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_surah.setText("Surah");
        getContentPane().add(Jlabel_surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 30));

        surah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        surah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الفاتحة", "البقرة", "آل عمران", "النّساء", "المائدة", "الانعام", "الأعراف", "الأنفال", "التوبة‎‎", "يونس", "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه", "الأنبياء", "الحجّ", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم", "لقمان", "السجدة", "الْأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر", "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الَأحقاف", "محمد", "الفتح", "الحجرات", "ق", "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة", "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحآقة", "المعارج", "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس", "التكوير", "الإنفطار", "المطففين", "الإنشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد", "الشمس", "اليل", "الضحى", "الإنشراح", "التينِ", "العلق", "القدرِ", "البينة", "الزلزلة", "العاديات", "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر", "اللهب", "الإخلاص", "الفلق", "الناس" }));
        surah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        surah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surahActionPerformed(evt);
            }
        });
        getContentPane().add(surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        hapus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hapus.setText("Hapus");
        hapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 70, -1));

        Jlabel_ayat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_ayat.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_ayat.setText("Ayat");
        getContentPane().add(Jlabel_ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 30));
        getContentPane().add(text_juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 30));

        kembali.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kembali.setText("kembali");
        kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 30));

        cari.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cari.setText("Cari");
        cari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 90, 40));

        edit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        edit.setText("Edit");
        edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 70, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel1.setText("Cek Hafalan Terakhir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 50));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg_cek_hafalan_terakhir_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        getContentPane().add(bg_cek_hafalan_terakhir_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        setSize(new java.awt.Dimension(668, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try { // hapus data
            String sql = "delete from cari where nim='" + text_nim.getText() + "'";
            java.sql.Connection conn = (java.sql.Connection) connect.koneksi.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data akan dihapus?");
            text_nim.setText("");
            text_hari_tanggal.setText("");
            text_juz.setText("");
            surah.setSelectedIndex(0);
            text_ayat.setText("");
        } catch (SQLException | HeadlessException e) {
        }
        GetData();
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new halaman_utama_admin().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        nime = text_nim.getText();
         try {
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql;
            sql = stm.executeQuery("select * from cari where nim=" + nime);
            if (sql.next()) {
                String nimm = sql.getString("nim");
                text_nim.setText(nimm);
                String harii = sql.getString("tanggal");
                text_hari_tanggal.setText(harii);
                String juzz = sql.getString("juz");
                text_juz.setText(juzz);
                String ayatt = sql.getString("ayat");
                text_ayat.setText(ayatt);
                String surahh = sql.getString("surah");
                switch (surahh) {
                    case "الفاتحة":
                        surah.setSelectedIndex(0);
                        break;
                    case "البقرة":
                        surah.setSelectedIndex(1);
                        break;
                    case "آل عمران":
                        surah.setSelectedIndex(2);
                        break;
                    case "النّساء":
                        surah.setSelectedIndex(3);
                        break;
                    case "المائدة":
                        surah.setSelectedIndex(4);
                        break;
                    case "الانعام":
                        surah.setSelectedIndex(5);
                        break;
                    case "الأعراف":
                        surah.setSelectedIndex(6);
                        break;
                    case "الأنفال":
                        surah.setSelectedIndex(7);
                        break;
                    case "التوبة‎‎":
                        surah.setSelectedIndex(8);
                        break;
                    case "يونس":
                        surah.setSelectedIndex(9);
                        break;
                    case "هود":
                        surah.setSelectedIndex(10);
                        break;
                    case "يوسف":
                        surah.setSelectedIndex(11);
                        break;
                    case "الرعد":
                        surah.setSelectedIndex(12);
                        break;
                    case "إبراهيم":
                        surah.setSelectedIndex(13);
                        break;
                    case "الحجر":
                        surah.setSelectedIndex(14);
                        break;
                    case "النحل":
                        surah.setSelectedIndex(15);
                        break;
                    case "الإسراء":
                        surah.setSelectedIndex(16);
                        break;
                    case "الكهف":
                        surah.setSelectedIndex(17);
                        break;
                    case "مريم":
                        surah.setSelectedIndex(18);
                        break;
                    case "طه":
                        surah.setSelectedIndex(19);
                        break;
                    case "الأنبياء":
                        surah.setSelectedIndex(20);
                        break;
                    case "الحجّ":
                        surah.setSelectedIndex(21);
                        break;
                    case "المؤمنون":
                        surah.setSelectedIndex(22);
                        break;
                    case "النور":
                        surah.setSelectedIndex(23);
                        break;
                    case "الفرقان":
                        surah.setSelectedIndex(24);
                        break;
                    case "الشعراء":
                        surah.setSelectedIndex(25);
                        break;
                    case "النمل":
                        surah.setSelectedIndex(26);
                        break;
                    case "القصص":
                        surah.setSelectedIndex(27);
                        break;
                    case "العنكبوت":
                        surah.setSelectedIndex(28);
                        break;
                    case "الروم":
                        surah.setSelectedIndex(29);
                        break;
                    case "لقمان":
                        surah.setSelectedIndex(30);
                        break;
                    case "السجدة":
                        surah.setSelectedIndex(31);
                        break;
                    case "الْأحزاب":
                        surah.setSelectedIndex(32);
                        break;
                    case "سبأ":
                        surah.setSelectedIndex(33);
                        break;
                    case "فاطر":
                        surah.setSelectedIndex(34);
                        break;
                    case "يس":
                        surah.setSelectedIndex(35);
                        break;
                    case "الصافات":
                        surah.setSelectedIndex(36);
                        break;
                    case "ص":
                        surah.setSelectedIndex(37);
                        break;
                    case "الزمر":
                        surah.setSelectedIndex(38);
                        break;
                    case "غافر":
                        surah.setSelectedIndex(39);
                        break;
                    case "فصلت":
                        surah.setSelectedIndex(40);
                        break;
                    case "الشورى":
                        surah.setSelectedIndex(41);
                        break;
                    case "الزخرف":
                        surah.setSelectedIndex(42);
                        break;
                    case "الدخان":
                        surah.setSelectedIndex(43);
                        break;
                    case "الجاثية":
                        surah.setSelectedIndex(44);
                        break;
                    case "الَأحقاف":
                        surah.setSelectedIndex(45);
                        break;
                    case "محمد":
                        surah.setSelectedIndex(46);
                        break;
                    case "الفتح":
                        surah.setSelectedIndex(47);
                        break;
                    case "الحجرات":
                        surah.setSelectedIndex(48);
                        break;
                    case "ق":
                        surah.setSelectedIndex(49);
                        break;
                    case "الذاريات":
                        surah.setSelectedIndex(50);
                        break;
                    case "الطور":
                        surah.setSelectedIndex(51);
                        break;
                    case "النجم":
                        surah.setSelectedIndex(52);
                        break;
                    case "القمر":
                        surah.setSelectedIndex(53);
                        break;
                    case "الرحمن":
                        surah.setSelectedIndex(54);
                        break;
                    case "الواقعة":
                        surah.setSelectedIndex(55);
                        break;
                    case "الحديد":
                        surah.setSelectedIndex(56);
                        break;
                    case "المجادلة":
                        surah.setSelectedIndex(57);
                        break;
                    case "الحشر":
                        surah.setSelectedIndex(58);
                        break;
                    case "الممتحنة":
                        surah.setSelectedIndex(59);
                        break;
                    case "الصف":
                        surah.setSelectedIndex(60);
                        break;
                    case "الجمعة":
                        surah.setSelectedIndex(61);
                        break;
                    case "المنافقون":
                        surah.setSelectedIndex(62);
                        break;
                    case "التغابن":
                        surah.setSelectedIndex(63);
                        break;
                    case "الطلاق":
                        surah.setSelectedIndex(64);
                        break;
                    case "التحريم":
                        surah.setSelectedIndex(65);
                        break;
                    case "الملك":
                        surah.setSelectedIndex(66);
                        break;
                    case "القلم":
                        surah.setSelectedIndex(67);
                        break;
                    case "الحآقة":
                        surah.setSelectedIndex(68);
                        break;
                    case "المعارج":
                        surah.setSelectedIndex(69);
                        break;
                    case "نوح":
                        surah.setSelectedIndex(70);
                        break;
                    case "الجن":
                        surah.setSelectedIndex(71);
                        break;
                    case "المزمل":
                        surah.setSelectedIndex(72);
                        break;
                    case "المدثر":
                        surah.setSelectedIndex(73);
                        break;
                    case "القيامة":
                        surah.setSelectedIndex(74);
                        break;
                    case "الإنسان":
                        surah.setSelectedIndex(75);
                        break;
                    case "المرسلات":
                        surah.setSelectedIndex(76);
                        break;
                    case "النبأ":
                        surah.setSelectedIndex(77);
                        break;
                    case "النازعات":
                        surah.setSelectedIndex(78);
                        break;
                    case "عبس":
                        surah.setSelectedIndex(79);
                        break;
                    case "التكوير":
                        surah.setSelectedIndex(80);
                        break;
                    case "الإنفطار":
                        surah.setSelectedIndex(81);
                        break;
                    case "المطففين":
                        surah.setSelectedIndex(82);
                        break;
                    case "الإنشقاق":
                        surah.setSelectedIndex(83);
                        break;
                    case "البروج":
                        surah.setSelectedIndex(84);
                        break;
                    case "الطارق":
                        surah.setSelectedIndex(85);
                        break;
                    case "الأعلى":
                        surah.setSelectedIndex(86);
                        break;
                    case "الغاشية":
                        surah.setSelectedIndex(87);
                        break;
                    case "الفجر":
                        surah.setSelectedIndex(88);
                        break;
                    case "البلد":
                        surah.setSelectedIndex(89);
                        break;
                    case "الشمس":
                        surah.setSelectedIndex(90);
                        break;
                    case "اليل":
                        surah.setSelectedIndex(91);
                        break;
                    case "الضحى":
                        surah.setSelectedIndex(92);
                        break;
                    case "الإنشراح":
                        surah.setSelectedIndex(93);
                        break;
                    case "التين":
                        surah.setSelectedIndex(94);
                        break;
                    case "العلق":
                        surah.setSelectedIndex(95);
                        break;
                    case "القدر":
                        surah.setSelectedIndex(96);
                        break;
                    case "البينة":
                        surah.setSelectedIndex(97);
                        break;
                    case "الزلزلة":
                        surah.setSelectedIndex(98);
                        break;
                    case "العاديات":
                        surah.setSelectedIndex(99);
                        break;
                    case "القارعة":
                        surah.setSelectedIndex(100);
                        break;
                    case "التكاثر":
                        surah.setSelectedIndex(101);
                        break;
                    case "العصر":
                        surah.setSelectedIndex(102);
                        break;
                    case "الهمزة":
                        surah.setSelectedIndex(103);
                        break;
                    case "الفيلِ":
                        surah.setSelectedIndex(104);
                        break;
                    case "قريش":
                        surah.setSelectedIndex(105);
                        break;
                    case "الماعون":
                        surah.setSelectedIndex(106);
                        break;
                    case "الكوثر":
                        surah.setSelectedIndex(107);
                        break;
                    case "الكافرون":
                        surah.setSelectedIndex(108);
                        break;
                    case "النصر":
                        surah.setSelectedIndex(109);
                        break;
                    case "اللهب":
                        surah.setSelectedIndex(110);
                        break;
                    case "الإخلاص":
                        surah.setSelectedIndex(111);
                        break;
                    case "الفلق":
                        surah.setSelectedIndex(112);
                        break;
                    case "الناس":
                        surah.setSelectedIndex(113);
                        break;

                    default:
                        break;
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cariActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE cari SET nim='" + text_nim.getText() + "',"
                    + "tanggal='" + text_hari_tanggal.getText() + "',"
                    + "juz='" + text_juz.getText() + "',"                  
                    + "ayat='" + text_ayat.getText() + "',"
                    + "surah='" + surah.getSelectedItem().toString()
                    + "' WHERE nim=" + text_nim.getText();
            Connection conn = connect.koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil disimpan");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void surahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cek_hafalan_terakhir_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_ayat;
    private javax.swing.JLabel Jlabel_juz;
    private javax.swing.JLabel Jlabel_nim;
    private javax.swing.JLabel Jlabel_surah;
    private javax.swing.JLabel Jlabel_tanggal;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg_cek_hafalan_terakhir_1;
    private javax.swing.JButton cari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    private javax.swing.JComboBox<String> surah;
    private javax.swing.JTextField text_ayat;
    private javax.swing.JTextField text_hari_tanggal;
    private javax.swing.JTextField text_juz;
    private javax.swing.JTextField text_nim;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
