import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author henyr
 */
public class cek_hafalan_terakhir extends javax.swing.JFrame {

    /**
     * Creates new form cek_hafalan_terakhir
     */
    public cek_hafalan_terakhir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void GetData() {
        try {
            
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql;
            sql = stm.executeQuery("select * from cari");

        } catch (Exception e) {
        }
    }
    String[] data;
    String nime = "";
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        ayat = new javax.swing.JLabel();
        big_user = new javax.swing.JLabel();
        text_ayat = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();
        label_surah = new javax.swing.JLabel();
        text_nim = new javax.swing.JTextField();
        hari_tanggal = new javax.swing.JLabel();
        text_hari_tanggal = new javax.swing.JTextField();
        surah = new javax.swing.JComboBox<>();
        juz = new javax.swing.JLabel();
        text_juz = new javax.swing.JTextField();
        nim = new javax.swing.JLabel();
        log_out = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bg_cek_hafalan_terakhir = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIM");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 367));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ayat.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        ayat.setForeground(new java.awt.Color(255, 255, 255));
        ayat.setText("Ayat");
        getContentPane().add(ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 50, -1));
        getContentPane().add(big_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        text_ayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ayatActionPerformed(evt);
            }
        });
        getContentPane().add(text_ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 80, 30));

        bt_cari.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        bt_cari.setText("CARI");
        bt_cari.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cariActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, 30));

        label_surah.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        label_surah.setForeground(new java.awt.Color(255, 255, 255));
        label_surah.setText("Surah");
        getContentPane().add(label_surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 70, 30));

        text_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nimActionPerformed(evt);
            }
        });
        getContentPane().add(text_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, 30));

        hari_tanggal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        hari_tanggal.setForeground(new java.awt.Color(255, 255, 255));
        hari_tanggal.setText("  Tanggal");
        hari_tanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        getContentPane().add(hari_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        text_hari_tanggal.setForeground(new java.awt.Color(153, 153, 153));
        text_hari_tanggal.setText("dd/mm/yy");
        text_hari_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_hari_tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(text_hari_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 190, 30));

        surah.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        surah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الفاتحة", "البقرة", "آل عمران", "النّساء", "المائدة", "الانعام", "الأعراف", "الأنفال", "التوبة‎‎", "يونس", "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه", "الأنبياء", "الحجّ", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم", "لقمان", "السجدة", "الْأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر", "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الَأحقاف", "محمد", "الفتح", "الحجرات", "ق", "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة", "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحآقة", "المعارج", "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس", "التكوير", "الإنفطار", "المطففين", "الإنشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد", "الشمس", "اليل", "الضحى", "الإنشراح", "التينِ", "العلق", "القدرِ", "البينة", "الزلزلة", "العاديات", "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر", "اللهب", "الإخلاص", "الفلق", "الناس" }));
        surah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surahActionPerformed(evt);
            }
        });
        getContentPane().add(surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 150, 30));

        juz.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        juz.setForeground(new java.awt.Color(255, 255, 255));
        juz.setText("Juz");
        getContentPane().add(juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 50, -1));

        text_juz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_juzActionPerformed(evt);
            }
        });
        getContentPane().add(text_juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 50, 30));

        nim.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nim.setForeground(new java.awt.Color(240, 240, 240));
        nim.setText("NIM");
        nim.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 40, -1));

        log_out.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        log_out.setText("LOG OUT");
        log_out.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        getContentPane().add(log_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel1.setText("Cek Hafalan Terakhir");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 50));

        bg_cek_hafalan_terakhir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        getContentPane().add(bg_cek_hafalan_terakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -3, 650, 370));

        setSize(new java.awt.Dimension(670, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_ayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ayatActionPerformed

    private void bt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cariActionPerformed
        nime = text_nim.getText();
         try {
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql;
            sql = stm.executeQuery("select * from cari where nim=" + nime);
            if (sql.next()) {
                String nimm = sql.getString("nim");
                text_nim.setText(nimm);
                String harii = sql.getString("tanggal");
                text_hari_tanggal.setText(harii);
                String juzz = sql.getString("juz");
                text_juz.setText(juzz);
                String ayatt = sql.getString("ayat");
                text_ayat.setText(ayatt);
                String surahh = sql.getString("surah");
                switch (surahh) {
                    case "الفاتحة":
                        surah.setSelectedIndex(0);
                        break;
                    case "البقرة":
                        surah.setSelectedIndex(1);
                        break;
                    case "آل عمران":
                        surah.setSelectedIndex(2);
                        break;
                    case "النّساء":
                        surah.setSelectedIndex(3);
                        break;
                    case "المائدة":
                        surah.setSelectedIndex(4);
                        break;
                    case "الانعام":
                        surah.setSelectedIndex(5);
                        break;
                    case "الأعراف":
                        surah.setSelectedIndex(6);
                        break;
                    case "الأنفال":
                        surah.setSelectedIndex(7);
                        break;
                    case "التوبة‎‎":
                        surah.setSelectedIndex(8);
                        break;
                    case "يونس":
                        surah.setSelectedIndex(9);
                        break;
                    case "هود":
                        surah.setSelectedIndex(10);
                        break;
                    case "يوسف":
                        surah.setSelectedIndex(11);
                        break;
                    case "الرعد":
                        surah.setSelectedIndex(12);
                        break;
                    case "إبراهيم":
                        surah.setSelectedIndex(13);
                        break;
                    case "الحجر":
                        surah.setSelectedIndex(14);
                        break;
                    case "النحل":
                        surah.setSelectedIndex(15);
                        break;
                    case "الإسراء":
                        surah.setSelectedIndex(16);
                        break;
                    case "الكهف":
                        surah.setSelectedIndex(17);
                        break;
                    case "مريم":
                        surah.setSelectedIndex(18);
                        break;
                    case "طه":
                        surah.setSelectedIndex(19);
                        break;
                    case "الأنبياء":
                        surah.setSelectedIndex(20);
                        break;
                    case "الحجّ":
                        surah.setSelectedIndex(21);
                        break;
                    case "المؤمنون":
                        surah.setSelectedIndex(22);
                        break;
                    case "النور":
                        surah.setSelectedIndex(23);
                        break;
                    case "الفرقان":
                        surah.setSelectedIndex(24);
                        break;
                    case "الشعراء":
                        surah.setSelectedIndex(25);
                        break;
                    case "النمل":
                        surah.setSelectedIndex(26);
                        break;
                    case "القصص":
                        surah.setSelectedIndex(27);
                        break;
                    case "العنكبوت":
                        surah.setSelectedIndex(28);
                        break;
                    case "الروم":
                        surah.setSelectedIndex(29);
                        break;
                    case "لقمان":
                        surah.setSelectedIndex(30);
                        break;
                    case "السجدة":
                        surah.setSelectedIndex(31);
                        break;
                    case "الْأحزاب":
                        surah.setSelectedIndex(32);
                        break;
                    case "سبأ":
                        surah.setSelectedIndex(33);
                        break;
                    case "فاطر":
                        surah.setSelectedIndex(34);
                        break;
                    case "يس":
                        surah.setSelectedIndex(35);
                        break;
                    case "الصافات":
                        surah.setSelectedIndex(36);
                        break;
                    case "ص":
                        surah.setSelectedIndex(37);
                        break;
                    case "الزمر":
                        surah.setSelectedIndex(38);
                        break;
                    case "غافر":
                        surah.setSelectedIndex(39);
                        break;
                    case "فصلت":
                        surah.setSelectedIndex(40);
                        break;
                    case "الشورى":
                        surah.setSelectedIndex(41);
                        break;
                    case "الزخرف":
                        surah.setSelectedIndex(42);
                        break;
                    case "الدخان":
                        surah.setSelectedIndex(43);
                        break;
                    case "الجاثية":
                        surah.setSelectedIndex(44);
                        break;
                    case "الَأحقاف":
                        surah.setSelectedIndex(45);
                        break;
                    case "محمد":
                        surah.setSelectedIndex(46);
                        break;
                    case "الفتح":
                        surah.setSelectedIndex(47);
                        break;
                    case "الحجرات":
                        surah.setSelectedIndex(48);
                        break;
                    case "ق":
                        surah.setSelectedIndex(49);
                        break;
                    case "الذاريات":
                        surah.setSelectedIndex(50);
                        break;
                    case "الطور":
                        surah.setSelectedIndex(51);
                        break;
                    case "النجم":
                        surah.setSelectedIndex(52);
                        break;
                    case "القمر":
                        surah.setSelectedIndex(53);
                        break;
                    case "الرحمن":
                        surah.setSelectedIndex(54);
                        break;
                    case "الواقعة":
                        surah.setSelectedIndex(55);
                        break;
                    case "الحديد":
                        surah.setSelectedIndex(56);
                        break;
                    case "المجادلة":
                        surah.setSelectedIndex(57);
                        break;
                    case "الحشر":
                        surah.setSelectedIndex(58);
                        break;
                    case "الممتحنة":
                        surah.setSelectedIndex(59);
                        break;
                    case "الصف":
                        surah.setSelectedIndex(60);
                        break;
                    case "الجمعة":
                        surah.setSelectedIndex(61);
                        break;
                    case "المنافقون":
                        surah.setSelectedIndex(62);
                        break;
                    case "التغابن":
                        surah.setSelectedIndex(63);
                        break;
                    case "الطلاق":
                        surah.setSelectedIndex(64);
                        break;
                    case "التحريم":
                        surah.setSelectedIndex(65);
                        break;
                    case "الملك":
                        surah.setSelectedIndex(66);
                        break;
                    case "القلم":
                        surah.setSelectedIndex(67);
                        break;
                    case "الحآقة":
                        surah.setSelectedIndex(68);
                        break;
                    case "المعارج":
                        surah.setSelectedIndex(69);
                        break;
                    case "نوح":
                        surah.setSelectedIndex(70);
                        break;
                    case "الجن":
                        surah.setSelectedIndex(71);
                        break;
                    case "المزمل":
                        surah.setSelectedIndex(72);
                        break;
                    case "المدثر":
                        surah.setSelectedIndex(73);
                        break;
                    case "القيامة":
                        surah.setSelectedIndex(74);
                        break;
                    case "الإنسان":
                        surah.setSelectedIndex(75);
                        break;
                    case "المرسلات":
                        surah.setSelectedIndex(76);
                        break;
                    case "النبأ":
                        surah.setSelectedIndex(77);
                        break;
                    case "النازعات":
                        surah.setSelectedIndex(78);
                        break;
                    case "عبس":
                        surah.setSelectedIndex(79);
                        break;
                    case "التكوير":
                        surah.setSelectedIndex(80);
                        break;
                    case "الإنفطار":
                        surah.setSelectedIndex(81);
                        break;
                    case "المطففين":
                        surah.setSelectedIndex(82);
                        break;
                    case "الإنشقاق":
                        surah.setSelectedIndex(83);
                        break;
                    case "البروج":
                        surah.setSelectedIndex(84);
                        break;
                    case "الطارق":
                        surah.setSelectedIndex(85);
                        break;
                    case "الأعلى":
                        surah.setSelectedIndex(86);
                        break;
                    case "الغاشية":
                        surah.setSelectedIndex(87);
                        break;
                    case "الفجر":
                        surah.setSelectedIndex(88);
                        break;
                    case "البلد":
                        surah.setSelectedIndex(89);
                        break;
                    case "الشمس":
                        surah.setSelectedIndex(90);
                        break;
                    case "اليل":
                        surah.setSelectedIndex(91);
                        break;
                    case "الضحى":
                        surah.setSelectedIndex(92);
                        break;
                    case "الإنشراح":
                        surah.setSelectedIndex(93);
                        break;
                    case "التين":
                        surah.setSelectedIndex(94);
                        break;
                    case "العلق":
                        surah.setSelectedIndex(95);
                        break;
                    case "القدر":
                        surah.setSelectedIndex(96);
                        break;
                    case "البينة":
                        surah.setSelectedIndex(97);
                        break;
                    case "الزلزلة":
                        surah.setSelectedIndex(98);
                        break;
                    case "العاديات":
                        surah.setSelectedIndex(99);
                        break;
                    case "القارعة":
                        surah.setSelectedIndex(100);
                        break;
                    case "التكاثر":
                        surah.setSelectedIndex(101);
                        break;
                    case "العصر":
                        surah.setSelectedIndex(102);
                        break;
                    case "الهمزة":
                        surah.setSelectedIndex(103);
                        break;
                    case "الفيلِ":
                        surah.setSelectedIndex(104);
                        break;
                    case "قريش":
                        surah.setSelectedIndex(105);
                        break;
                    case "الماعون":
                        surah.setSelectedIndex(106);
                        break;
                    case "الكوثر":
                        surah.setSelectedIndex(107);
                        break;
                    case "الكافرون":
                        surah.setSelectedIndex(108);
                        break;
                    case "النصر":
                        surah.setSelectedIndex(109);
                        break;
                    case "اللهب":
                        surah.setSelectedIndex(110);
                        break;
                    case "الإخلاص":
                        surah.setSelectedIndex(111);
                        break;
                    case "الفلق":
                        surah.setSelectedIndex(112);
                        break;
                    case "الناس":
                        surah.setSelectedIndex(113);
                        break;

                    default:
                        break;
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_cariActionPerformed

    private void text_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nimActionPerformed

    private void text_hari_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_hari_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_hari_tanggalActionPerformed

    private void text_juzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_juzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_juzActionPerformed

    private void surahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surahActionPerformed
        //case disini
        String nime = text_nim.getText();

        try {
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql;
            sql = stm.executeQuery("select * from cari where nim=" + nime);
            if (sql.next()) {
                String nimm = sql.getString("nim");
                text_nim.setText(nimm);
                String harii = sql.getString("hari/tanggal");
                text_hari_tanggal.setText(harii);
                String juzz = sql.getString("juz");
                text_juz.setText(juzz);
                String ayatt = sql.getString("ayat");
                text_ayat.setText(ayatt);
                String surahh = sql.getString("surah");
                switch (surahh) {
                    case "الفاتحة":
                        surah.setSelectedIndex(0);
                        break;
                    case "البقرة":
                        surah.setSelectedIndex(1);
                        break;
                    case "آل عمران":
                        surah.setSelectedIndex(2);
                        break;
                    case "النّساء":
                        surah.setSelectedIndex(3);
                        break;
                    case "المائدة":
                        surah.setSelectedIndex(4);
                        break;
                    case "الانعام":
                        surah.setSelectedIndex(5);
                        break;
                    case "الأعراف":
                        surah.setSelectedIndex(6);
                        break;
                    case "الأنفال":
                        surah.setSelectedIndex(7);
                        break;
                    case "التوبة‎‎":
                        surah.setSelectedIndex(8);
                        break;
                    case "يونس":
                        surah.setSelectedIndex(9);
                        break;
                    case "هود":
                        surah.setSelectedIndex(10);
                        break;
                    case "يوسف":
                        surah.setSelectedIndex(11);
                        break;
                    case "الرعد":
                        surah.setSelectedIndex(12);
                        break;
                    case "إبراهيم":
                        surah.setSelectedIndex(13);
                        break;
                    case "الحجر":
                        surah.setSelectedIndex(14);
                        break;
                    case "النحل":
                        surah.setSelectedIndex(15);
                        break;
                    case "الإسراء":
                        surah.setSelectedIndex(16);
                        break;
                    case "الكهف":
                        surah.setSelectedIndex(17);
                        break;
                    case "مريم":
                        surah.setSelectedIndex(18);
                        break;
                    case "طه":
                        surah.setSelectedIndex(19);
                        break;
                    case "الأنبياء":
                        surah.setSelectedIndex(20);
                        break;
                    case "الحجّ":
                        surah.setSelectedIndex(21);
                        break;
                    case "المؤمنون":
                        surah.setSelectedIndex(22);
                        break;
                    case "النور":
                        surah.setSelectedIndex(23);
                        break;
                    case "الفرقان":
                        surah.setSelectedIndex(24);
                        break;

                    case "الشعراء":
                        surah.setSelectedIndex(25);
                        break;
                    case "النمل":
                        surah.setSelectedIndex(26);
                        break;
                    case "القصص":
                        surah.setSelectedIndex(27);
                        break;
                    case "العنكبوت":
                        surah.setSelectedIndex(28);
                        break;
                    case "الروم":
                        surah.setSelectedIndex(29);
                        break;
                    case "لقمان":
                        surah.setSelectedIndex(30);
                        break;
                    case "السجدة":
                        surah.setSelectedIndex(31);
                        break;
                    case "الْأحزاب":
                        surah.setSelectedIndex(32);
                        break;
                    case "سبأ":
                        surah.setSelectedIndex(33);
                        break;
                    case "فاطر":
                        surah.setSelectedIndex(34);
                        break;
                    case "يس":
                        surah.setSelectedIndex(35);
                        break;
                    case "الصافات":
                        surah.setSelectedIndex(36);
                        break;
                    case "ص":
                        surah.setSelectedIndex(37);
                        break;
                    case "الزمر":
                        surah.setSelectedIndex(38);
                        break;
                    case "غافر":
                        surah.setSelectedIndex(39);
                        break;
                    case "فصلت":
                        surah.setSelectedIndex(40);
                        break;
                    case "الشورى":
                        surah.setSelectedIndex(41);
                        break;
                    case "الزخرف":
                        surah.setSelectedIndex(42);
                        break;
                    case "الدخان":
                        surah.setSelectedIndex(43);
                        break;
                    case "الجاثية":
                        surah.setSelectedIndex(44);
                        break;
                    case "الَأحقاف":
                        surah.setSelectedIndex(45);
                        break;
                    case "محمد":
                        surah.setSelectedIndex(46);
                        break;
                    case "الفتح":
                        surah.setSelectedIndex(47);
                        break;
                    case "الحجرات":
                        surah.setSelectedIndex(48);
                        break;
                    case "ق":
                        surah.setSelectedIndex(49);
                        break;
                    case "الذاريات":
                        surah.setSelectedIndex(50);
                        break;
                    case "الطور":
                        surah.setSelectedIndex(51);
                        break;
                    case "النجم":
                        surah.setSelectedIndex(52);
                        break;
                    case "القمر":
                        surah.setSelectedIndex(53);
                        break;
                    case "الرحمن":
                        surah.setSelectedIndex(54);
                        break;
                    case "الواقعة":
                        surah.setSelectedIndex(55);
                        break;
                    case "الحديد":
                        surah.setSelectedIndex(56);
                        break;
                    case "المجادلة":
                        surah.setSelectedIndex(57);
                        break;
                    case "الحشر":
                        surah.setSelectedIndex(58);
                        break;
                    case "الممتحنة":
                        surah.setSelectedIndex(59);
                        break;
                    case "الصف":
                        surah.setSelectedIndex(60);
                        break;
                    case "الجمعة":
                        surah.setSelectedIndex(61);
                        break;
                    case "المنافقون":
                        surah.setSelectedIndex(62);
                        break;
                    case "التغابن":
                        surah.setSelectedIndex(63);
                        break;
                    case "الطلاق":
                        surah.setSelectedIndex(64);
                        break;
                    case "التحريم":
                        surah.setSelectedIndex(65);
                        break;
                    case "الملك":
                        surah.setSelectedIndex(66);
                        break;
                    case "القلم":
                        surah.setSelectedIndex(67);
                        break;
                    case "الحآقة":
                        surah.setSelectedIndex(68);
                        break;
                    case "المعارج":
                        surah.setSelectedIndex(69);
                        break;
                    case "نوح":
                        surah.setSelectedIndex(70);
                        break;
                    case "الجن":
                        surah.setSelectedIndex(71);
                        break;
                    case "المزمل":
                        surah.setSelectedIndex(72);
                        break;
                    case "المدثر":
                        surah.setSelectedIndex(73);
                        break;
                    case "القيامة":
                        surah.setSelectedIndex(74);
                        break;
                    case "الإنسان":
                        surah.setSelectedIndex(75);
                        break;
                    case "المرسلات":
                        surah.setSelectedIndex(76);
                        break;
                    case "النبأ":
                        surah.setSelectedIndex(77);
                        break;
                    case "النازعات":
                        surah.setSelectedIndex(78);
                        break;
                    case "عبس":
                        surah.setSelectedIndex(79);
                        break;
                    case "التكوير":
                        surah.setSelectedIndex(80);
                        break;
                    case "الإنفطار":
                        surah.setSelectedIndex(81);
                        break;
                    case "المطففين":
                        surah.setSelectedIndex(82);
                        break;
                    case "الإنشقاق":
                        surah.setSelectedIndex(83);
                        break;
                    case "البروج":
                        surah.setSelectedIndex(84);
                        break;
                    case "الطارق":
                        surah.setSelectedIndex(85);
                        break;
                    case "الأعلى":
                        surah.setSelectedIndex(86);
                        break;
                    case "الغاشية":
                        surah.setSelectedIndex(87);
                        break;
                    case "الفجر":
                        surah.setSelectedIndex(88);
                        break;
                    case "البلد":
                        surah.setSelectedIndex(89);
                        break;
                    case "الشمس":
                        surah.setSelectedIndex(90);
                        break;
                    case "اليل":
                        surah.setSelectedIndex(91);
                        break;
                    case "الضحى":
                        surah.setSelectedIndex(92);
                        break;
                    case "الإنشراح":
                        surah.setSelectedIndex(93);
                        break;
                    case "التين":
                        surah.setSelectedIndex(94);
                        break;
                    case "العلق":
                        surah.setSelectedIndex(95);
                        break;
                    case "القدر":
                        surah.setSelectedIndex(96);
                        break;
                    case "البينة":
                        surah.setSelectedIndex(97);
                        break;
                    case "الزلزلة":
                        surah.setSelectedIndex(98);
                        break;
                    case "العاديات":
                        surah.setSelectedIndex(99);
                        break;
                    case "القارعة":
                        surah.setSelectedIndex(100);
                        break;
                    case "التكاثر":
                        surah.setSelectedIndex(101);
                        break;
                    case "العصر":
                        surah.setSelectedIndex(102);
                        break;
                    case "الهمزة":
                        surah.setSelectedIndex(103);
                        break;
                    case "الفيلِ":
                        surah.setSelectedIndex(104);
                        break;
                    case "قريش":
                        surah.setSelectedIndex(105);
                        break;
                    case "الماعون":
                        surah.setSelectedIndex(106);
                        break;
                    case "الكوثر":
                        surah.setSelectedIndex(107);
                        break;
                    case "الكافرون":
                        surah.setSelectedIndex(108);
                        break;
                    case "النصر":
                        surah.setSelectedIndex(109);
                        break;
                    case "اللهب":
                        surah.setSelectedIndex(110);
                        break;
                    case "الإخلاص":
                        surah.setSelectedIndex(111);
                        break;
                    case "الفلق":
                        surah.setSelectedIndex(112);
                        break;
                    case "الناس":
                        surah.setSelectedIndex(113);
                        break;

                    default:
                        break;

                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_surahActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        new awal().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cek_hafalan_terakhir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cek_hafalan_terakhir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayat;
    private javax.swing.JLabel bg_cek_hafalan_terakhir;
    private javax.swing.JLabel big_user;
    private javax.swing.JButton bt_cari;
    private javax.swing.JLabel hari_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel juz;
    private javax.swing.JLabel label_surah;
    private javax.swing.JButton log_out;
    private javax.swing.JLabel nim;
    private javax.swing.JComboBox<String> surah;
    private javax.swing.JTextField text_ayat;
    private javax.swing.JTextField text_hari_tanggal;
    private javax.swing.JTextField text_juz;
    private javax.swing.JTextField text_nim;
    // End of variables declaration//GEN-END:variables
}
