

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author shafira halmahera
 */
public class daftar extends javax.swing.JFrame {

    /**
     * Creates new form Daftar
     */
    public daftar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        logo_htq = new javax.swing.JLabel();
        logo_uin = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        nim = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        txt_pw = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        bg_daftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 367));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(logo_htq, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));
        getContentPane().add(logo_uin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        nama.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        nama.setText("NAMA");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, 30));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 180, 30));

        nim.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        nim.setText("NIM");
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, -1));
        getContentPane().add(txt_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 180, 30));

        username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        username.setText("USERNAME");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 190, 40));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 180, 30));

        password.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 180, 30));

        simpan.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 120, 40));

        keluar.setBackground(new java.awt.Color(204, 204, 255));
        keluar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        keluar.setText("KELUAR");
        keluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 40));

        bg_daftar.setBackground(new java.awt.Color(204, 204, 255));
        bg_daftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        bg_daftar.setMaximumSize(new java.awt.Dimension(660, 367));
        bg_daftar.setMinimumSize(new java.awt.Dimension(660, 367));
        bg_daftar.setPreferredSize(new java.awt.Dimension(660, 367));
        bg_daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bg_daftarActionPerformed(evt);
            }
        });
        getContentPane().add(bg_daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 370));

        setSize(new java.awt.Dimension(669, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bg_daftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bg_daftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bg_daftarActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
   new awal ().setVisible(true);
   this.setVisible(false);
    }//GEN-LAST:event_keluarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
//        // TODO add your handling code here:
        try {
            String sql = "UPDATE login_user SET nim='" + txt_nim.getText() + "',"
                    + "nama='" + txt_nama.getText() + "',"
                    + "username='" + txt_user.getText() + "',"                    
                    + "password='" + txt_pw.getText() + "'";
            Connection conn = connect.koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan, "+ "\n"
                    + "Silahkan klik tombol keluar dan masuk ke menu login ");
            txt_nim.setText("");
            txt_nama.setText("");
            txt_user.setText("");
            
            txt_pw.setText("");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        

    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new daftar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bg_daftar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel logo_htq;
    private javax.swing.JLabel logo_uin;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel password;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
