
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author amirul
 */
public class data_hafalan_mahasiswa extends javax.swing.JFrame {

    private DefaultTableModel model;
    public static Statement stm;
    public static ResultSet res;
    public static ResultSet data1 = null;

    /**
     * Creates new form tambahkan_hafalan
     */
    public data_hafalan_mahasiswa() {
        initComponents();
        tampildata();
    }

    private void tampildata() {
        try {
            Object[] judul_kolom = {"nim", "tanggal", "juz", "ayat", "surah"};
            model = new DefaultTableModel(null, judul_kolom);
            tabel.setModel(model);

            Connection conn = (Connection) connect.koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            model.getDataVector().removeAllElements();

            data1 = stt.executeQuery("SELECT * from cari");
            while (data1.next()) {
                Object[] data = {
                    data1.getString("nim"),
                    data1.getString("tanggal"),
                    data1.getString("juz"),
                    data1.getString("ayat"),
                    data1.getString("surah"),};
                model.addRow(data);
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    private void cariData(String key) {
        try {
            Object[] judul_kolom = {"nim", "tanggal", "juz", "ayat", "surah"};
            model = new DefaultTableModel(null, judul_kolom);
            tabel.setModel(model);

            Connection conn = (Connection) connect.koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            model.getDataVector().removeAllElements();

            data1 = stt.executeQuery("SELECT * from cari WHERE nim LIKE '%" + key + "%' ");
            while (data1.next()) {
                Object[] data = {
                    data1.getString("nim"),
                    data1.getString("tanggal"),
                    data1.getString("juz"),
                    data1.getString("ayat"),
                    data1.getString("surah"),};
                model.addRow(data);
            }
        } catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        Jlabel_nim = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        bg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        nim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nimKeyReleased(evt);
            }
        });
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 140, 30));

        Jlabel_nim.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_nim.setText("NIM");
        getContentPane().add(Jlabel_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, 30));

        kembali.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kembali.setText("kembali");
        kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 30));

        tabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 150, 630, 110));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel2.setText("DATA SELURUH HAFALAN ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 400, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 380));

        setSize(new java.awt.Dimension(669, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new halaman_utama_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void nimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nimKeyReleased
        // TODO add your handling code here:
        String key = nim.getText();
        System.out.println(key);

        if (key != "") {
            cariData(key);
        } else {
            tampildata();
        }
    }//GEN-LAST:event_nimKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_hafalan_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_hafalan_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_hafalan_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_hafalan_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_hafalan_mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_nim;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nim;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
