
import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henyr
 */
public class halaman_login_user extends javax.swing.JFrame {

    /**
     * Creates new form halaman_login_user
     */
    public halaman_login_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_login_user = new javax.swing.JLabel();
        logo_uin = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        htq = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        bt_daftarulang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        text_pw = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        bg_login_user.setBackground(new java.awt.Color(51, 51, 0));
        bg_login_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_uin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo uin.png"))); // NOI18N
        getContentPane().add(logo_uin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        password.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        htq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logohtq.png"))); // NOI18N
        getContentPane().add(htq, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 100, 80));

        username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        username.setText("USERNAME");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 86, -1, 40));
        getContentPane().add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 160, 30));

        bt_login.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        bt_login.setText("LOGIN");
        bt_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        getContentPane().add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, -1));

        bt_daftarulang.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        bt_daftarulang.setText("DAFTAR ULANG");
        bt_daftarulang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_daftarulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_daftarulangActionPerformed(evt);
            }
        });
        getContentPane().add(bt_daftarulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/small_user.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, 30));

        text_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pwActionPerformed(evt);
            }
        });
        getContentPane().add(text_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 160, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kunci.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        setSize(new java.awt.Dimension(669, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        String un = text_username.getText();
        String ps = text_pw.getText();

        //        try {
            //            PreparedStatement statement = (Connection)koneksi.koneksiDB().prepareStatement("select * from login_user where username= '" + un + "' and password= '" + ps + "'");
            //            ResultSet result = statement.executeQuery();
            try {
                Connection con = (Connection) connect.koneksi.koneksiDB();
                Statement stm = con.createStatement();
                ResultSet sql = stm.executeQuery("select * from login_user");

                if (sql.next()) {
                    if (text_username.getText().equals(sql.getString("username"))
                        && text_pw.getText().equals(sql.getString("password"))) {
                        JOptionPane.showMessageDialog(null, "Berhasil login");
                        new halaman_utama_user().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Username atau Password Salah");
                    }
                }
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Gagal Login");
            }
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_daftarulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_daftarulangActionPerformed
        new daftar().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_bt_daftarulangActionPerformed

    private void text_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_login_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new halaman_login_user().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_login_user;
    private javax.swing.JButton bt_daftarulang;
    private javax.swing.JButton bt_login;
    private javax.swing.JLabel htq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logo_uin;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField text_pw;
    private javax.swing.JTextField text_username;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
