/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henyr
 */
public class halaman_utama_user extends javax.swing.JFrame {

    /**
     * Creates new form halaman_utama_user
     */
    public halaman_utama_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_putih = new javax.swing.JLabel();
        cek_hafalan = new javax.swing.JButton();
        bgutama_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_putih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/big user putih.png"))); // NOI18N
        getContentPane().add(user_putih, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 100, 80));

        cek_hafalan.setBackground(new java.awt.Color(255, 255, 255));
        cek_hafalan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cek_hafalan.setText("Cek Hafalan Terakhir Saya"); // NOI18N
        cek_hafalan.setActionCommand("Cek Hafalan \n.\n\nTerakhir Saya");
        cek_hafalan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.orange, new java.awt.Color(0, 102, 51)));
        cek_hafalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cek_hafalanActionPerformed(evt);
            }
        });
        getContentPane().add(cek_hafalan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 250, 90));

        bgutama_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgkartun.jpg"))); // NOI18N
        getContentPane().add(bgutama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(677, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cek_hafalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cek_hafalanActionPerformed
        // TODO add your handling code here:
        new cek_hafalan_terakhir().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_cek_hafalanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_utama_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_utama_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_utama_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_utama_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_utama_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgutama_user;
    private javax.swing.JButton cek_hafalan;
    private javax.swing.JLabel user_putih;
    // End of variables declaration//GEN-END:variables
}
