
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author shafira halmahera
 */
public class halaman_login_admin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    public halaman_login_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logo_uin = new javax.swing.JLabel();
        logo_htq = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_pw = new javax.swing.JTextField();
        daftar_ulang = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bg_form_login_admin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("LOGIN ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(logo_uin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(logo_htq, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 105, 30, 30));

        username.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        username.setText("USERNAME");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 180, 30));

        password.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        password.setText("PASSWORD");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 30, 40));
        getContentPane().add(txt_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, 30));

        daftar_ulang.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        daftar_ulang.setText("DAFTAR ULANG");
        daftar_ulang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        daftar_ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftar_ulangActionPerformed(evt);
            }
        });
        getContentPane().add(daftar_ulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 40));

        login.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        login.setText("LOGIN");
        login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Goudy Stout", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("HALAMAN LOGIN ADMIN");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 40));

        bg_form_login_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        bg_form_login_admin.setMaximumSize(new java.awt.Dimension(660, 367));
        bg_form_login_admin.setMinimumSize(new java.awt.Dimension(660, 367));
        bg_form_login_admin.setPreferredSize(new java.awt.Dimension(660, 367));
        getContentPane().add(bg_form_login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 360));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        setSize(new java.awt.Dimension(667, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void daftar_ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftar_ulangActionPerformed
        // TODO add your handling code here:
        new daftar_admin ().setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_daftar_ulangActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String un = txt_user.getText();
        String ps = txt_pw.getText();

//        try {
//            PreparedStatement statement = (Connection)koneksi.koneksiDB().prepareStatement("select * from login_user where username= '" + un + "' and password= '" + ps + "'");
//            ResultSet result = statement.executeQuery();
            try {
            Connection con = (Connection) connect.koneksi.koneksiDB();
            Statement stm = con.createStatement();
            ResultSet sql = stm.executeQuery("select * from login_admin");
            
            if (sql.next()) {
                if (txt_user.getText().equals(sql.getString("username"))
                        && txt_pw.getText().equals(sql.getString("password"))) {
                    JOptionPane.showMessageDialog(null, "Berhasil login");
                    new halaman_utama_admin().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Username atau Password Salah");
                }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal Login");
        }
                         
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_login_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_form_login_admin;
    private javax.swing.JButton daftar_ulang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo_htq;
    private javax.swing.JLabel logo_uin;
    private javax.swing.JLabel password;
    private javax.swing.JTextField txt_pw;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel user;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
