
import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henyr
 */
public class tambah_hafalan extends javax.swing.JFrame {

    /**
     * Creates new form tambah_hafalan
     */
    public tambah_hafalan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nim = new javax.swing.JTextField();
        ayat = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        Jlabel_nim = new javax.swing.JLabel();
        Jlabel_tanggal = new javax.swing.JLabel();
        Jlabel_juz = new javax.swing.JLabel();
        Jlabel_surah = new javax.swing.JLabel();
        surah = new javax.swing.JComboBox<>();
        Jlabel_ayat = new javax.swing.JLabel();
        juz = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, 30));

        ayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayatActionPerformed(evt);
            }
        });
        getContentPane().add(ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 90, 30));

        tanggal.setForeground(new java.awt.Color(102, 102, 102));
        tanggal.setText("dd/mm/yy");
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 30));

        Jlabel_nim.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Jlabel_nim.setText("NIM");
        getContentPane().add(Jlabel_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 50, 30));

        Jlabel_tanggal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_tanggal.setText("Tanggal");
        getContentPane().add(Jlabel_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 30));

        Jlabel_juz.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_juz.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_juz.setText("Juz");
        getContentPane().add(Jlabel_juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 30));

        Jlabel_surah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_surah.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_surah.setText("Surah");
        getContentPane().add(Jlabel_surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 30));

        surah.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        surah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "الفاتحة", "البقرة", "آل عمران", "النّساء", "المائدة", "الانعام", "الأعراف", "الأنفال", "التوبة‎‎", "يونس", "هود", "يوسف", "الرعد", "إبراهيم", "الحجر", "النحل", "الإسراء", "الكهف", "مريم", "طه", "الأنبياء", "الحجّ", "المؤمنون", "النور", "الفرقان", "الشعراء", "النمل", "القصص", "العنكبوت", "الروم", "لقمان", "السجدة", "الْأحزاب", "سبأ", "فاطر", "يس", "الصافات", "ص", "الزمر", "غافر", "فصلت", "الشورى", "الزخرف", "الدخان", "الجاثية", "الَأحقاف", "محمد", "الفتح", "الحجرات", "ق", "الذاريات", "الطور", "النجم", "القمر", "الرحمن", "الواقعة", "الحديد", "المجادلة", "الحشر", "الممتحنة", "الصف", "الجمعة", "المنافقون", "التغابن", "الطلاق", "التحريم", "الملك", "القلم", "الحآقة", "المعارج", "نوح", "الجن", "المزمل", "المدثر", "القيامة", "الإنسان", "المرسلات", "النبأ", "النازعات", "عبس", "التكوير", "الإنفطار", "المطففين", "الإنشقاق", "البروج", "الطارق", "الأعلى", "الغاشية", "الفجر", "البلد", "الشمس", "اليل", "الضحى", "الإنشراح", "التينِ", "العلق", "القدرِ", "البينة", "الزلزلة", "العاديات", "القارعة", "التكاثر", "العصر", "الهمزة", "الفيل", "قريش", "الماعون", "الكوثر", "الكافرون", "النصر", "اللهب", "الإخلاص", "الفلق", "الناس" }));
        surah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        Jlabel_ayat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Jlabel_ayat.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel_ayat.setText("Ayat");
        getContentPane().add(Jlabel_ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 30));
        getContentPane().add(juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 40, 30));

        simpan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        simpan.setText("Simpan");
        simpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 311, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel2.setText("Tambahkan Hafalan Mahasantri");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 50));

        kembali.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        kembali.setText("kembali");
        kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        setSize(new java.awt.Dimension(667, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        

        try {
            String sql = "insert into cari values('" + nim.getText() + "',"
                    + "'" + tanggal.getText() + "',"
                    + "'" + juz.getText() + "',"
                    + "'" + ayat.getText() + "',"
                    + "'" + surah.getSelectedItem().toString() + "')";
            Connection conn = connect.koneksi.koneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "berhasil disimpan");
            nim.setText("");
            tanggal.setText("");
            juz.setText("");
            surah.setSelectedIndex(0);
            ayat.setText("");
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
//   String NIM="", harii="", juzz="", surahh="", ayatt="";
//       NIM= nim.getText();
//        harii = tanggal.getText();
//        juzz = juz.getText();
//        surahh = (String) surah.getSelectedItem();
//        ayatt = ayat.getText();
//        Connection con;
//        try {
//            con = connect.koneksi.koneksiDB();
//        } catch (SQLException ex) {
//            Logger.getLogger(tambah_hafalan.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if ("".equals(NIM) || "".equals(harii) || "".equals(juzz) || "".equals(surahh)
//                || "".equals(ayatt)) {
//            JOptionPane.showMessageDialog(null, "Mohon isi data dengan lengkap !!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
//        } else {
//            try {
//                String sql = "insert into cari values (?,?,?,?,?,?,?)";
//                PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);
//                stat.setString(1, NIM);
//                stat.setString(2, harii);
//                stat.setString(3, juzz);
//                stat.setString(4, surahh);
//                stat.setString(5, ayatt);
//                stat.executeUpdate();
//                JOptionPane.showMessageDialog(null, "BERHASIL menyimpan data !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
//                reset();
//
//            } catch (HeadlessException | SQLException e) {
//                JOptionPane.showMessageDialog(null, "GAGAL menyimpan data !", "Informasi", JOptionPane.INFORMATION_MESSAGE);
//            }
//        }

    }//GEN-LAST:event_simpanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new halaman_utama_admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void ayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_hafalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_hafalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_hafalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_hafalan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tambah_hafalan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlabel_ayat;
    private javax.swing.JLabel Jlabel_juz;
    private javax.swing.JLabel Jlabel_nim;
    private javax.swing.JLabel Jlabel_surah;
    private javax.swing.JLabel Jlabel_tanggal;
    private javax.swing.JTextField ayat;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField juz;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField nim;
    private javax.swing.JButton simpan;
    private javax.swing.JComboBox<String> surah;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
